# Generated by Django 4.1.9 on 2023-09-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="options",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_option",
                    models.TextField(default=None, max_length=20000, null=True),
                ),
                (
                    "column_option",
                    models.TextField(default=None, max_length=20000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="question_to_option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.IntegerField(default=None, null=True)),
                ("option_id", models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(default=None, max_length=20000, null=True),
                ),
                ("section", models.CharField(default=None, max_length=100, null=True)),
                ("prd_usage", models.BooleanField(default=False, null=True)),
                ("market_trend", models.BooleanField(default=False, null=True)),
                (
                    "customer_satisfaction",
                    models.BooleanField(default=False, null=True),
                ),
                ("purchase_behaviour", models.BooleanField(default=False, null=True)),
                ("price_perception", models.BooleanField(default=False, null=True)),
                ("brand_awareness", models.BooleanField(default=False, null=True)),
                ("brand_perception", models.BooleanField(default=False, null=True)),
                ("adv_effectiveness", models.BooleanField(default=False, null=True)),
                ("prd_development", models.BooleanField(default=False, null=True)),
                ("market_seg", models.BooleanField(default=False, null=True)),
                ("customer_feedback", models.BooleanField(default=False, null=True)),
                ("comp_analysis", models.BooleanField(default=False, null=True)),
                ("market_expansion", models.BooleanField(default=False, null=True)),
                (
                    "distribution_channels",
                    models.BooleanField(default=False, null=True),
                ),
                ("customer_preferences", models.BooleanField(default=False, null=True)),
                ("compliance_issues", models.BooleanField(default=False, null=True)),
                ("market_potential", models.BooleanField(default=False, null=True)),
                ("psychographics", models.BooleanField(default=False, null=True)),
                ("tech_adoption", models.BooleanField(default=False, null=True)),
                (
                    "social_responsibility",
                    models.BooleanField(default=False, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="statement_to_question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement_id", models.IntegerField(default=None, null=True)),
                ("question_id", models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="statements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statement",
                    models.TextField(default=None, max_length=20000, null=True),
                ),
                (
                    "type_of_research",
                    models.TextField(default=None, max_length=200, null=True),
                ),
                (
                    "research_topic",
                    models.TextField(default=None, max_length=200, null=True),
                ),
                ("domain", models.TextField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
